Fix regression running against pwd using `.`
This regression was introduced in #15,
and causes errors like:
```
ValueError: '/Users/aagrawal/src/myproject/somefile.py' does not start with ''
```